{% set name = "contourpy" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/contourpy-{{ version }}.tar.gz
  sha256: e53046c3863828d21d531cc3b53786e6580eb1ba02477e8681009b6aa0870b21

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - pybind11 >=2.6                      # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
  host:
    - pip
    - pybind11 >=2.6
    - python
    - setuptools >=42
  run:
    - numpy >=1.16
    - python

test:
  imports:
    - contourpy
    - contourpy.util
  commands:
    - pip check
    - python -c "import contourpy as c; c.contour_generator(z=[[0, 1], [2, 3]]).lines(0.9)"
  requires:
    - pip

about:
  description: |
    ContourPy is a Python library for calculating contours of 2D quadrilateral
    grids.  It is written in C++11 and wrapped using pybind11.
  doc_url: https://contourpy.readthedocs.io
  home: https://github.com/contourpy/contourpy
  summary: Python library for calculating contours of 2D quadrilateral grids.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ianthomas23
