{% set name = "contourpy" %}
{% set version = "1.0.8.dev1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/contourpy-{{ version }}.tar.gz
  #sha256: d8165a088d31798b59e91117d1f5fc3df8168d8b48c4acc10fc0df0d0bdbcc5e
  git_url: https://github.com/contourpy/contourpy.git
  git_rev: 9821ecb3000046d39f9a1c894165f9aeb04bda9d

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation

requirements:
  build:
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
  host:
    - pip
    - meson >=1.1.0
    - meson-python >=0.13.1
    - ninja
    - pybind11 >=2.10.4
    - python
  run:
    - numpy >=1.16
    - python

test:
  imports:
    - contourpy
    - contourpy.util
  commands:
    - pip check
    - python -c "import contourpy as c; c.contour_generator(z=[[0, 1], [2, 3]]).lines(0.9)"
  requires:
    - pip

about:
  description: |
    ContourPy is a Python library for calculating contours of 2D quadrilateral
    grids.  It is written in C++11 and wrapped using pybind11.
  doc_url: https://contourpy.readthedocs.io
  home: https://github.com/contourpy/contourpy
  summary: Python library for calculating contours of 2D quadrilateral grids.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ianthomas23
